#cloud-config

# init stage
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false # true
    plain_text_passwd: password
    ssh_import_id:
      - gh:mami0tsu

# config stage
timezone: Asia/Tokyo

# final stage
package_update: true
package_upgrade: true
package_reboot_if_required: true
final_message: |
  cloud-init has finished
  version: $version
  timestamp: $timestamp
  datasource: $datasource
  uptime: $uptime
